global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'api-gateway'
    scrape_interval: 5s
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'session-service'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['session-service-1:8001', 'session-service-2:8002', 'session-service-3:8003']

  - job_name: 'user-service'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['user-service-1:8004', 'user-service-2:8005', 'user-service-3:8006']


     